### PR TITLE
Add https and wss support

### LINKED ISSUE #4: Remote server https and wss not supported
I am running comfy ui on a cloud server and it exposes only https and wss.

This can be easily resolved by editing client.py and network.py. A checkbox or dropdown list to choose between secure connection would be the simplest.

https://github.com/Acly/krita-ai-diffusion/blob/8e14748df6d2c0ee0255882b715f3dfa2e0ad7be/ai_diffusion/client.py#L110
https://github.com/Acly/krita-ai-diffusion/blob/8e14748df6d2c0ee0255882b715f3dfa2e0ad7be/ai_diffusion/network.py#L65

### PR DESCRIPTION
**Pull request by gergelyszaz**
Fixes #4

### CODE REVIEW

**Comment by gergelyszaz** [comment]
Only tested the https and wss connection. Should still work if not the full url is provided, only the hostname.

**Comment by gergelyszaz** [comment]
Might as well trim the trailing slash in an url.
https://awesome-site.com/ is still problematic.

**Comment by gergelyszaz** [comment]
Something is not right yet... the connection is created but I don't get the image.

**Comment by Acly** [comment]
Hm I also use extra_model_paths.yaml and had duplicates before without issues I think.

Anyway, PR looks good, thank you!

**Pull request merged**
