### PR TITLE
Use SamplerCustomAdvanced node to allow new schedulers usage (including AlingYourSteps)

### PR DESCRIPTION
**Pull request by Danamir**
Here is an update replacing the old `KSamplerAdvanced` by the more recent additions to base ComfyUI : `SamplerCustomAdvanced`, `*Scheduler`, `SplitSigmas`, `RandomNoise`, `CFGGuider`, `KSamplerSelect`.

The functionalities are exactly the same, ie. : `steps`, `start_at_step`, `cfg`, `add_noise`, etc. But it also allow the use of various new scheduler nodes : `BasicScheduler`, `AlignYourStepsScheduler`, `GITSScheduler`, `PolyexponentialScheduler` which are not otherwise available in the schedulers list of the old sampler node.

Coincidentally this allows the usage of the new iPNDM V sampler with Align Your Steps scheduler, which works really well : 

```json
    "iPNDM V": {
        "sampler": "ipndm_v",
        "scheduler": "align_your_steps",
        "steps": 20,
        "cfg": 6.0
    }
```

### CODE REVIEW

**Comment by Danamir** [comment]
This development works with my custom installation of ComfyUI, but I'm not sure the bundled version with krita-ai-diffusion has those, to be tested.

And sadly the latest ComfyUI version seems to have trouble loading the lightweights `workflow.json` generated by the plugin, significantly increasing the difficulty to debug.

**Comment by Danamir** [comment]
Here is a discussion on iPNDM samplers : https://github.com/comfyanonymous/ComfyUI/discussions/3799

**Comment by Acly** [comment]
I tried AYS when I tested all the distilled low-step Lora for last update, and thought it was kind of meh. Haven't tried out IPNDM yet though. And there is also CFG++ now...

**Comment by Danamir** [comment]
Yeah, I would not have done the development for AYS only. But I'm guessing more and more of the future scheduler will be ported to ComfyUI as `*Scheduler` nodes, so I did this to mostly to future-proof the sampling method used. 

I always has been a fervent user of DPM++ SDE (not the 2M/3M variants) because I felt it had more coherency, responded well to LoRAs, and had less anatomy problems. Right now I'm testing iPNDM V with AYS/GITS, and for me it can safely replace DPM++ 2M/3M SDE, having zero color artifacts problems at low steps (~18). DPM++ SDE still has a little advantage overall, but is twice as slow. 

I did not see CFG++, is it implemented in base ComfyUI or as a custom node ?

**Comment by Danamir** [comment]
There you go, CFG++ support. 

Note : I thought it was only usable with a cfg between `0.0` and `1.0`, but the ComfyUI implementation ranges from `1.0` to `2.0`, cf. : https://github.com/comfyanonymous/ComfyUI/discussions/3844 

I'm having good results with AYS and `1.6` cfg : 

```json
    "Euler CFG++ AYS": {
        "sampler": "euler_cfgpp",
        "scheduler": "align_your_steps",
        "steps": 20,
        "cfg": 1.6
    }
```

**Comment by Danamir** [comment]
Damn, found some more doc and I could have used directly the `euler_pp` and `euler_ancestral_pp` in `BasicScheduler`. 😅  The code evolves so fast it is difficult to get everything right on the first try.

Tested : `euler_pp` corresponds to `SamplerEulerCFGpp` with `version=alternative`. The `version=regular` is much more contrasted. I'll leave it as it is is for now do do some more tests.

**Comment by Danamir** [comment]
I don't know if I'm missing something, but `euler 6.0 cfg` gives the exact same result as `euler_pp 3.0 cfg++`. Same results at 20 steps and 50 steps. I don't see the point of CFG++ then...

At least the "regular" SamplerEulerCFGpp offers different results, but impossible to say if those are better or not.

Not impressed by CFG++ so far.

**Comment by Acly** [comment]
Yup, not sure what euler_pp is about either. The regular SamplerEulerCFGpp works but I don't exactly find it easier to use. Anyway I guess we can keep it, just in case someone asks.

**Comment by Danamir** [comment]
After some more testing, I keep coming back to GITS scheduler ! At 20 steps and lower (when refining), I find it almost always better than Karras, which was my go-to scheduler. Above 20 steps, AYS and GITS perform equally well, so in fine GITS is more versatile.

Either with DPM++ SDE for a boost of quality, DPM++ 2M for speed, or Euler A for sharpness... it's really good.

iPNDM V is not bad at all, good to have as a choice, but I would not select it as my first general sampler.

**Comment by Acly** [comment]
AYS/GITS is definitely better for 12~18 steps range. I'll probably make it the default for the "Fast" preset. It uses UniPC which actually works okay with these, though iPNDM might be better.

**Pull request merged**
